
export const ACTIVE_DAY = 'ACTIVE_DAY'
export const INITIALIZE_DAYS = 'INITIALIZE_DAYS'
export const LOAD_DAYS = 'LOAD_DAYS'
export const RESET_DAYS = 'RESET_DAYS'
export const RESET_DAYS_SAVE_OFF = 'RESET_DAYS_SAVE_OFF'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_TO_STORE = 'USER_TO_STORE'
export const USER_RESET = 'USER_RESET'
export const USER_REPORT = 'USER_REPORT'

export const STAGE_HOME = 'STAGE_HOME'

export const LUXURY_LIST = 'LUXURY_LIST'
export const HOMES_LIST = 'HOMES_LIST'
export const HOMES_LIST_RESET = 'HOMES_LIST_RESET'

export const STORE_REVIEWS = 'STORE_REVIEWS'
export const ADD_REVIEW = 'ADD_REVIEW'

export const FILTER_PROVINCE = 'FILTER_PROVINCE'
export const FILTER_CAPACITY = 'FILTER_CAPACITY'
export const FILTER_GENERAL = 'FILTER_GENERAL'


export const ADD_HOME = 'ADD_HOME'
export const ADD_HOME_STEPS = 'ADD_HOME_STEPS'
export const HOME_DAYS = 'HOME_DAYS'

export const RESERVE = 'RESERVE'

export const EXPLORE_SPECIAL_OFFERS = 'EXPLORE_SPECIAL_OFFERS'
export const EXPLORE_PROMOTED_CITIES = 'EXPLORE_PROMOTED_CITIES'
export const EXPLORE_CITY_01 = 'EXPLORE_CITY_01'
export const EXPLORE_CITY_02 = 'EXPLORE_CITY_02'
