export const USER_LOCAL_CHECK = 'USER_LOCAL_CHECK'
export const USER_LOCAL_CHECK_FOUNDED = 'USER_LOCAL_CHECK_FOUNDED'
export const USER_LOCAL_CHECK_NOT_FOUNDED = 'USER_LOCAL_CHECK_NOT_FOUNDED'

export const USER_ONLINE_CHECK = 'USER_ONLINE_CHECK'
export const USER_ONLINE_CHECK_FOUNDED = 'USER_ONLINE_CHECK_FOUNDED'
export const USER_ONLINE_CHECK_NOT_FOUNDED = 'USER_ONLINE_CHECK_NOT_FOUNDED'

export const ACTIVE_DAY = 'ACTIVE_DAY'
export const INITIALIZE_DAYS = 'INITIALIZE_DAYS'
export const LOAD_DAYS = 'LOAD_DAYS'
export const RESET_DAYS = 'RESET_DAYS'


export const USER_REGISTER = 'USER_REGISTER'
export const USER_TO_STORE = 'USER_TO_STORE'
