
export const ACTIVE_DAY = 'ACTIVE_DAY'
export const INITIALIZE_DAYS = 'INITIALIZE_DAYS'
export const LOAD_DAYS = 'LOAD_DAYS'
export const RESET_DAYS = 'RESET_DAYS'


export const USER_REGISTER = 'USER_REGISTER'
export const USER_TO_STORE = 'USER_TO_STORE'
export const USER_RESET = 'USER_RESET'
export const USER_REPORT = 'USER_REPORT'

export const STAGE_HOME = 'STAGE_HOME'

export const LUXURY_LIST = 'LUXURY_LIST'

export const STORE_REVIEWS = 'STORE_REVIEWS'
export const ADD_REVIEW = 'ADD_REVIEW'

export const FILTER_PROVINCE = 'FILTER_PROVINCE'
export const FILTER_CAPACITY = 'FILTER_CAPACITY'
export const FILTER_GENERAL_FILTERS = 'FILTER_GENERAL_FILTERS'
// export const FILTER_INSTANCE_RESERVE = 'FILTER_INSTANCE_RESERVE'
// export const FILTER_PRICE = 'FILTER_PRICE'
// export const FILTER_ENTIRE = 'FILTER_ENTIRE'
// export const FILTER_PRIVATE_ROOM = 'FILTER_PRIVATE_ROOM'
// export const FILTER_SHARED_ROOM = 'FILTER_SHARED_ROOM'
// export const FILTER_LUXURY = 'FILTER_LUXURY'
// export const FILTER_ROOMS = 'FILTER_ROOMS'
// export const FILTER_BEDS = 'FILTER_BEDS'
// export const FILTER_BATHROOMS = 'FILTER_BATHROOMS'
// export const FILTER_WIFI = 'FILTER_WIFI'
// export const FILTER_TV = 'FILTER_TV'
// export const FILTER_ACCESSORIES = 'FILTER_ACCESSORIES'
// export const FILTER_KITCHEN = 'FILTER_KITCHEN'
// export const FILTER_WASHING_MACHINE = 'FILTER_WASHING_MACHINE'
// export const FILTER_COOLER = 'FILTER_COOLER'
// export const FILTER_PARKING_LOT = 'FILTER_PARKING_LOT'
// export const FILTER_CELEBRATION_ALLOWED = 'FILTER_CELEBRATION_ALLOWED'
// export const FILTER_PETS_ALLOWED = 'FILTER_PETS_ALLOWED'
// export const FILTER_SMOKING_ALLOWED = 'FILTER_SMOKING_ALLOWED'


export const HOMES_LIST = 'HOMES_LIST'
